# application.yml
# tomcat
server:
  port: 8080
  servlet:
    context-path: /dagachi
    session:
      timeout: 30m
    
#spring
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: dagachi
    password: dagachi
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: C:/workspaces/spring_workspace/dagachi/src/main/webapp/resources/upload
  mail:
    host: smtp.gmail.com
    port: 587
    username: khsso102649@gmail.com
    password: yjuikbjezgbyosyw
    properties:
      mail:
        smtp:
          auth: true
          required: true
        connectiontimeout: 500
        timeout: 5000
        writetimeout: 5000
      auth-code-expiration-millis: 1800000
  security:
    oauth2:
      client: 
        registration: 
          kakao:
            client-id: 0b08c9c74b754bc22377c45ec5ce2736
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id
      
            
      
#logback
logging:
  level:
    root: info
    '[com.dagachi.app]': debug
    
#mybatis
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  type-aliases-package: com.dagachi.app, org.springframework.security.core.authority
  # type-handlers-package: com.dagachi.project.common.typehandler
  mapper-locations: classpath*:mapper/**/*-mapper.xml
 
 
      
# oauth
oauth:
  kakao:
    authorize-uri: https://kauth.kakao.com/oauth/authorize/
    redirect-uri: http://localhost:8080/spring/oauth/kakao/callback.do
    rest-api-key: 0b08c9c74b754bc22377c45ec5ce2736
    token-uri: https://kauth.kakao.com/oauth/token
    scope: profile_nickname, account_email, profile_image
    resource-uri-host: https://kapi.kakao.com


    
    
    
    