# application.yml
# tomcat
server:
  port: 8080
  servlet:
    context-path: /dagachi
    session:
      timeout: 30m
    
#spring
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: dagachi
    password: dagachi
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: C:/workspaces/spring_workspace/dagachi/src/main/webapp/resources/upload

            
      
#logback
logging:
  level:
    root: info
    '[com.dagachi.app]': debug
    
#mybatis
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  # type-aliases-package: com.dagachi.project, org.springframework.security.core.authority
  # type-handlers-package: com.dagachi.project.common.typehandler
  mapper-locations: classpath*:mapper/**/*-mapper.xml
    

    
    
    
    
    